# @package _global_

# to execute this experiment run:
# python -m iid.material_diffusion

defaults:
  - /logger: wandb
  - /model: material
  - /environment@_here_: default

# ======================== DATAMODULE ============================

data:
  dataset_cfg:
    root: /home/disk2/dataset/render_data/test/
    features_to_include: [ "origin" ]
  include_metadata: True

output:
  folder: output
  as_dataset: False

# ======================== ENVIRONMENT ============================

task_name: material_diffusion

seed: 0

device: auto